Add ‘Journal of Blow Molding Update’ enl to PMM
base-cms-newsletters/endeavor-business-media pull request #249
Opened 2020-10-27 15:20 UTC by Alixers505

https://southcomm.atlassian.net/browse/DEV-313

![screenshot-0 0 0 0_19437-2020 10 27-11_12_39](https://user-images.githubusercontent.com/6343242/97322682-6a972600-1846-11eb-9b06-2061cfc996b8.png)

2020-10-28 20:01 UTC, CaitlynKnudsvig requested changes
I glanced at the ticket, and regarding her last comment: we can just hard-code that last block on the newsletter for them if she gives you the info or the HTML for it.  We do that for a few newsletters in both systems that have static info that won't be updated from deployment-to-deployment.

Looks like it's a screenshot of another newsletter, so she can probably just snag the HTML for it at and we can dump it at the bottom of the template, above the footer.

2020-10-29 14:21 UTC, Alixers505 commented on tenants/plasticsmachinerymagazine/templates/journal-of-blow-molding-update.marko
> +      button-text-style=buttonTextStyle
I assumed the different button was an oversight because it was different from the other buttons, but I'll ask her.

2020-10-29 14:51 UTC, Alixers505 commented
Converted to draft because requester wants an additional component added to the template.

2020-10-29 15:19 UTC, CaitlynKnudsvig commented on tenants/plasticsmachinerymagazine/templates/journal-of-blow-molding-update.marko
> +      button-text-style=buttonTextStyle
lol totally was just an oversight on her part, thought so.  Thanks for checking to be sure!

2020-11-06 16:03 UTC, CaitlynKnudsvig commented on packages/common/components/style-b/blocks/image-only-header.marko
> +          </else>
You shouldn't really need this check, because if there's a `config.headerLeft.src` it will hit the first half of the template in the `<if(config && config.headerLeft)>` check

2020-11-06 16:04 UTC, Alixers505 commented on packages/common/components/style-b/blocks/image-only-header.marko
> +          </else>
ack, I missed that. gratzi

2020-11-06 16:06 UTC, CaitlynKnudsvig approved these changes

2020-11-06 16:11 UTC, merged